---
all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    project_root: "{{ playbook_dir }}/.."
    replica_set_name: rs0
    mongo_image: "mongo:7.0.14"
    mongo_nodes:
      - name: mongo1
        port: 27017
      - name: mongo2
        port: 27018
      - name: mongo3
        port: 27019
